name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - arch: x86_64
            platform: amd64
          - arch: aarch64
            platform: arm64
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: harbor.cloud.dillen.dev/docker/tonistiigi/binfmt:latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders
      - name: Setup tag for Docker image
        id: vars
        run: |
          echo "image_tag=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          provenance: false
          tags: ghcr.io/dillendev/distroless/cc-debian11-libpq:${{ matrix.platform }}-${{ env.image_tag }}
          build-args: ARCH=${{ matrix.arch }}
          platforms: linux/${{ matrix.platform }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.9.1
        with:
          image-ref: ghcr.io/dillendev/distroless/cc-debian11-libpq:${{ matrix.platform }}-${{ env.image_tag }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  manifest:
    runs-on: self-hosted
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: docker context create builders
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: harbor.cloud.dillen.dev/docker/tonistiigi/binfmt:latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: builders
      - name: Setup tag for Docker image
        id: vars
        run: |
          echo "image_tag=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Create and push manifest
        run: |
          docker manifest create ghcr.io/dillendev/distroless/cc-debian11-libpq:${{ env.image_tag }} \
            --amend ghcr.io/dillendev/distroless/cc-debian11-libpq:amd64-${{ env.image_tag }} \
            --amend ghcr.io/dillendev/distroless/cc-debian11-libpq:arm64-${{ env.image_tag }} && \
            docker manifest push ghcr.io/dillendev/distroless/cc-debian11-libpq:${{ env.image_tag }}
